name: 'judopay/ktlint-install'
description: 'Installs ktlint for a Kotlin project, caching the ktlint binary'
runs:
  using: composite
  steps:
  - name: Restore Cache
    id: cache-restore
    uses: actions/cache/restore@v4
    with:
      path: /usr/local/bin/ktlint
      key: ktlint-1.7.1
  - name: Install Ktlint
    if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
    run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.7.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
    shell: bash
  - name: Store Ktlint Cache
    if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
    uses: actions/cache/save@v4
    with:
      path: /usr/local/bin/ktlint
      key: ktlint-1.7.1
