name: iOS Build and Test

on:
  workflow_call:
    secrets:
      ios_app_store_connect_api_key:
        required: true
        description: API key for App Store Connect for code signing
      match_password:
        required: true
        description: Password for Fastlane match, for retrieving code signing certificates
      sonar_token:
        required: true
        description: Token for SonarCloud authentication
      ssh_key_github:
        required: true
        description: SSH key for accessing Github repositories

jobs:
  build_and_test:
    runs-on: macos-14
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up SSH Key
      uses: Judopay/github-actions/actions/ssh-agent@master
      with:
        ssh-private-key-base64: ${{ secrets.ssh_key_github }}
    - name: Run Build
      uses: maierj/fastlane-action@v3.1.0
      env:
        APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.ios_app_store_connect_api_key }}
        MATCH_PASSWORD: ${{ secrets.match_password }}
        XCODE_DERIVED_DATA_PATH: ${{ runner.temp }}/xcode/derived_data
      with:
        lane: build
    - name: Run Tests
      uses: maierj/fastlane-action@v3.1.0
      env:
        XCODE_DERIVED_DATA_PATH: ${{ runner.temp }}/xcode/derived_data
      with:
        lane: test
    - name: Run Sonar Scan
      uses: Judopay/github-actions/actions/sonar-scan@master
      with:
        sonar-token: ${{ secrets.sonar_token }}
        uses-xccov: "true"
