name: 'judopay/pod-install'
description: 'Runs pod install for an iOS project, caching Pods directory'
inputs:
  podfile-paths:
    description: 'Comma separated paths of Podfiles to run install on'
    required: true
runs:
  using: composite
  steps:
  - name: Restore Pod Cache
    id: pod-cache-restore
    uses: actions/cache/restore@v4
    with:
      path: '**/Pods'
      key: ${{ hashFiles('**/Podfile.lock') }}
  - name: Install Pods
    if: ${{ steps.pod-cache-restore.outputs.cache-hit != 'true' }}
    run: ${{ github.action_path }}/install.sh
    shell: bash
  - name: Store Pod Cache
    if: ${{ steps.scan-for-podfiles.outputs.PODFILE_LOCKS != '' && steps.pod-cache-restore.outputs.cache-hit != 'true' }}
    uses: actions/cache/save@v4
    with:
      path: '**/Pods'
      key: ${{ hashFiles('**/Podfile.lock') }}
