name: 'judopay/ssh-agent'
description: 'Run `ssh-agent` and load an SSH key'
inputs:
  ssh-private-key-base64:
    description: 'Base64 encoded SSH key to register in the SSH agent'
    required: true
runs:
  using: composite
  steps:
  - name: Set up SSH Agent
    run: |
      mkdir -p ~/.ssh
      echo ${{ inputs.ssh-private-key }} | base64 --decode > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh-add -D
      ssh-add ~/.ssh/id_rsa
      ssh-keyscan github.com > ~/.ssh/known_hosts
      git config --global user.name 'judo-ci'
      git config --global user.email 'devops@judopay.com'
    shell: bash
branding:
  icon: key
  color: purple
