name: 'judopay/ssh-agent'
description: 'Run `ssh-agent` and load an SSH key'
inputs:
  ssh-private-key-base64:
    description: 'Base64 encoded SSH key to register in the SSH agent'
    required: true
runs:
  using: composite
  steps:
  - name: Set up SSH Agent
    run: run.sh
    shell: bash
branding:
  icon: key
  color: purple
