name: iOS Test Sample Apps on Simulator
on:
  workflow_call:
jobs:
  build_and_test:
    runs-on: macos-15
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Ruby
      if: ${{ hashFiles('Gemfile.lock') != '' }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version-file: .nvmrc
    - name: Yarn Install
      if: ${{ hashFiles('yarn.lock') != '' }}
      run: yarn install --immutable
    - name: Brew Tap
      run: brew tap wix/brew
    - name: Brew Install
      uses: gerlero/brew-install@v1
      with:
        packages: applesimutils
    - name: Restore Sample Apps
      uses: actions/download-artifact@v5
      with:
        name: ios-sample-apps
        path: ${{ runner.temp }}/fastlane_output
    - name: Run Tests
      uses: maierj/fastlane-action@v3.1.0
      env:
        XCODE_DERIVED_DATA_PATH: ${{ runner.temp }}/xcode/derived_data
      with:
        lane: test_sample_apps_simulator
        options: '{ "platform": "ios"}'
