name: iOS Test Sample Apps with Firebase
on:
  workflow_call:
    secrets:
      google_cloud_service_account_key:
        required: true
        description: JSON key for Google Cloud service account for Firebase authentication
jobs:
  build_and_test:
    runs-on: macos-14
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Google Cloud Authentication
      uses: google-github-actions/auth@v2
      with:
        create_credentials_file: true
        credentials_json: ${{ secrets.google_cloud_service_account_key }}
    - name: Set up Ruby
      if: ${{ hashFiles('Gemfile.lock') != '' }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Download Instrumentation Test Packages
      run: gsutil cp -r gs://${{ vars.firebase_results_bucket }}/ios-instrumention-test-packages/* ${{ runner.temp }}/fastlane_output
      shell: bash
    - name: Run Instrumentation Tests on Firebase
      uses: maierj/fastlane-action@v3.1.0
      env:
        GOOGLE_CLOUD_PROJECT: ${{ vars.firebase_gcp_project }}
        FL_OUTPUT_DIR: ${{ runner.temp }}/fastlane_output
      with:
        lane: test_sample_apps_firebase
