name: iOS Test Sample Apps on Simulator
on:
  workflow_call:
    secrets:
      google_cloud_service_account_key:
        required: true
        description: JSON key for Google Cloud service account for Firebase authentication
      ios_app_store_connect_api_key:
        required: true
        description: API key for App Store Connect for code signing
      match_password:
        required: true
        description: Password for Fastlane match, for retrieving code signing certificates
      mobile_testing_judo_api_secret:
        required: true
        description: Judo API secret for mobile testing
      mobile_testing_judo_api_token:
        required: true
        description: Judo API token for mobile testing
      mobile_testing_judo_id:
        required: true
        description: Judo ID for mobile testing
      mobile_testing_ravelin_mock_server_url:
        required: true
        description: Ravelin mock server URL for mobile testing
      mobile_testing_ravelin_public_key:
        required: true
        description: Ravelin public key for mobile testing
      ssh_key_github:
        required: true
        description: SSH key for accessing Github repositories
      staging_domain:
        required: true
        description: Staging environment domain name for mobile testing
jobs:
  build_and_test:
    runs-on: macos-15
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Ruby
      if: ${{ hashFiles('Gemfile.lock') != '' }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version-file: .nvmrc
    - name: Yarn Install
      if: ${{ hashFiles('yarn.lock') != '' }}
      run: yarn install --immutable
    - name: Brew Tap
      run: brew tap wix/brew
    - name: Brew Install
      uses: gerlero/brew-install@v1
      with:
        packages: applesimutils
    - name: Restore Sample Apps
      uses: actions/download-artifact@v5
      with:
        name: ios-sample-apps
        path: ${{ runner.temp }}/fastlane_output
    - uses: valeriangalliat/action-sshd-cloudflared@v4
      env:
        AUTHORIZED_KEYS: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMO1rzPAE5E+M3R06HI2AMovE4hMJExbKMSDhXRg7jM4 test@testenv
        APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: true
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: 69a6de7a-a6bf-47e3-e053-5b8c7c11a4d1
        APP_STORE_CONNECT_API_KEY_KEY_ID: 9554PR33AC
        APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.ios_app_store_connect_api_key }}
        CODE_SIGNING_IDENTITY_ID: 95V535S6TQ
        FL_OUTPUT_DIR: ${{ runner.temp }}/fastlane_output
        JUDO_API_ID: ${{ secrets.mobile_testing_judo_id }}
        JUDO_API_SECRET: ${{ secrets.mobile_testing_judo_api_secret }}
        JUDO_API_TOKEN: ${{ secrets.mobile_testing_judo_api_token }}
        MATCH_GIT_URL: git@github.com:Judopay/JudoKit-iOS-SigningCertificates.git
        MATCH_PASSWORD: ${{ secrets.match_password }}
        RAVELIN_MOCK_SERVER_URL: ${{ secrets.mobile_testing_ravelin_mock_server_url }}
        RSA_PUBLIC_KEY: ${{ secrets.mobile_testing_ravelin_public_key }}
        STAGING_HOST_NAME: ${{ secrets.staging_domain }}
        XCODE_DERIVED_DATA_PATH: ${{ runner.temp }}/xcode/derived_data
    - name: Run Tests
      env: 
        FL_OUTPUT_DIR: ${{ runner.temp }}/fastlane_output
        XCODE_DERIVED_DATA_PATH: ${{ runner.temp }}/xcode/derived_data
      run: |
        bundle exec fastlane test_sample_apps_simulator platform:ios || true
        xcrun simctl spawn booted log show --info --debug --predicate 'processImagePath contains "CoreSimulatorBridge"'
    # - name: Run Tests
    #   uses: maierj/fastlane-action@v3.1.0
    #   env:
    #     FL_OUTPUT_DIR: ${{ runner.temp }}/fastlane_output
    #     XCODE_DERIVED_DATA_PATH: ${{ runner.temp }}/xcode/derived_data
    #   with:
    #     lane: test_sample_apps_simulator
    #     options: '{ "platform": "ios"}'
