name: iOS Build and Test
on:
  workflow_call:
    secrets:
      ios_app_store_connect_api_key:
        required: true
        description: API key for App Store Connect for code signing
      match_password:
        required: true
        description: Password for Fastlane match, for retrieving code signing certificates
      sonar_token:
        required: true
        description: Token for SonarCloud authentication
      ssh_key_github:
        required: true
        description: SSH key for accessing Github repositories
jobs:
  build_and_test:
    runs-on: macos-14
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up SSH Key
      uses: Judopay/github-actions/actions/ssh-agent@master
      with:
        ssh-private-key-base64: ${{ secrets.ssh_key_github }}
    - name: Set up Ruby
      if: ${{ hashFiles('Gemfile.lock') != '' }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Carthage Bootstrap
      if: ${{ hashFiles('Cartfile.resolved') != '' }}
      uses: Judopay/github-actions/actions/carthage-bootstrap@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Pod Install
      uses: Judopay/github-actions/actions/pod-install@master
    - name: Brew Install
      uses: gerlero/brew-install@v1
      with:
        packages: clang-format
    - name: Run Build
      uses: maierj/fastlane-action@v3.1.0
      env:
        APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: true
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: 69a6de7a-a6bf-47e3-e053-5b8c7c11a4d1
        APP_STORE_CONNECT_API_KEY_KEY_ID: 9554PR33AC
        APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.ios_app_store_connect_api_key }}
        CODE_SIGNING_IDENTITY_ID: 95V535S6TQ
        MATCH_GIT_URL: git@github.com:Judopay/JudoKit-iOS-SigningCertificates.git
        MATCH_PASSWORD: ${{ secrets.match_password }}
        STAGING_HOST_NAME: ${{ secrets.staging_domain }}
        XCODE_COMPILATION_DB_PATH: ${{ runner.temp }}/xcode/compilation_database
        XCODE_DERIVED_DATA_PATH: ${{ runner.temp }}/xcode/derived_data
      with:
        lane: build
    - name: Run Tests
      uses: maierj/fastlane-action@v3.1.0
      env:
        XCODE_DERIVED_DATA_PATH: ${{ runner.temp }}/xcode/derived_data
      with:
        lane: test
    - name: Run Sonar Scan
      uses: Judopay/github-actions/actions/sonar-scan@master
      with:
        sonar-token: ${{ secrets.sonar_token }}
        uses-xccov: "true"
