name: iOS Test Sample Apps with BrowserStack
on:
  workflow_call:
    secrets:
      browserstack_username:
        description: The user to authenticate with BrowserStack
        required: true
      browserstack_access_key:
        description: The access key to authenticate with BrowserStack
        required: true
      google_cloud_service_account_key:
        description: JSON key for Google Cloud service account for GCS authentication
        required: true
jobs:
  test_sample_apps:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Google Cloud Authentication
      uses: google-github-actions/auth@v2
      with:
        create_credentials_file: true
        credentials_json: ${{ secrets.google_cloud_service_account_key }}
        project_id: ${{ vars.firebase_gcp_project }}
    - name: Set up Ruby
      if: ${{ hashFiles('Gemfile.lock') != '' }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Download Instrumentation Test Packages & Sample Apps
      run: |
        mkdir -p ${{ runner.temp }}/fastlane_output
        gsutil cp -r gs://${{ vars.firebase_results_bucket }}/ios-instrumention-test-packages/* ${{ runner.temp }}/fastlane_output
        gsutil cp -r gs://${{ vars.firebase_results_bucket }}/ios-sample-apps/* ${{ runner.temp }}/fastlane_output
      shell: bash
    - name: Run Instrumentation Tests on BrowserStack
      uses: maierj/fastlane-action@v3.1.0
      env:
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.browserstack_access_key }}
        BROWSERSTACK_USERNAME: ${{ secrets.browserstack_username }}
        FL_OUTPUT_DIR: ${{ runner.temp }}/fastlane_output
      with:
        lane: test_sample_apps_browserstack
