name: iOS Test Sample Apps on Simulator
on:
  workflow_call:
jobs:
  build_and_test:
    runs-on: macos-15
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Ruby
      if: ${{ hashFiles('Gemfile.lock') != '' }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version-file: .nvmrc
    - name: Yarn Install
      if: ${{ hashFiles('yarn.lock') != '' }}
      run: yarn install --immutable
    - name: Brew Tap
      run: brew tap wix/brew
    - name: Brew Install
      uses: gerlero/brew-install@v1
      with:
        packages: applesimutils
    - name: Restore Sample Apps
      uses: actions/download-artifact@v5
      with:
        name: ios-sample-apps
        path: ${{ runner.temp }}/fastlane_output
    - uses: valeriangalliat/action-sshd-cloudflared@v4
      env:
        AUTHORIZED_KEYS: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMO1rzPAE5E+M3R06HI2AMovE4hMJExbKMSDhXRg7jM4 test@test
    - name: Run Tests
      env: 
        FL_OUTPUT_DIR: ${{ runner.temp }}/fastlane_output
        XCODE_DERIVED_DATA_PATH: ${{ runner.temp }}/xcode/derived_data
      run: |
        bundle exec fastlane test_sample_apps_simulator platform:ios || true
        xcrun simctl spawn booted log show --info --debug --predicate 'processImagePath contains "CoreSimulatorBridge"'
    # - name: Run Tests
    #   uses: maierj/fastlane-action@v3.1.0
    #   env:
    #     FL_OUTPUT_DIR: ${{ runner.temp }}/fastlane_output
    #     XCODE_DERIVED_DATA_PATH: ${{ runner.temp }}/xcode/derived_data
    #   with:
    #     lane: test_sample_apps_simulator
    #     options: '{ "platform": "ios"}'
