name: iOS Test Sample Apps with Firebase
on:
  workflow_call:
    inputs:
      firebase_matrix_label:
        description: Label for the Firebase test matrix
        required: true
        type: string
    secrets:
      google_cloud_service_account_key:
        description: JSON key for Google Cloud service account for Firebase authentication
        required: true
jobs:
  test_sample_apps:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Google Cloud Authentication
      uses: google-github-actions/auth@v2
      with:
        create_credentials_file: true
        credentials_json: ${{ secrets.google_cloud_service_account_key }}
    - name: Set up Ruby
      if: ${{ hashFiles('Gemfile.lock') != '' }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ vars.firebase_project_id }}
    - name: Download Instrumentation Test Packages
      run: |
        mkdir -p ${{ runner.temp }}/fastlane_output
        gsutil cp -r gs://${{ vars.firebase_results_bucket }}/ios-instrumention-test-packages/* ${{ runner.temp }}/fastlane_output
      shell: bash
    - name: Run Instrumentation Tests on Firebase
      uses: maierj/fastlane-action@v3.1.0
      env:
        FL_OUTPUT_DIR: ${{ runner.temp }}/fastlane_output
        FIREBASE_MATRIX_LABEL: ${{ inputs.firebase_matrix_label }}
        FIREBASE_TEST_RESULTS_BUCKET: ${{ vars.firebase_results_bucket }}
      with:
        lane: test_sample_apps_firebase
